sudo: false
language: python
python:
  - "2.7"
cache:
  directories:
    - $HOME/.pip-cache/
matrix:
  include:
  - python: "2.6"
    env: TOX_ENV=py26-dj14
  - python: "2.7"
    env: TOX_ENV=py27-dj17
  - python: "3.3"
    env: TOX_ENV=py33-dj17
  - python: "3.6"
    env: TOX_ENV=py36-dj20
install:
  - pip install --upgrade pip
  - pip install tox==1.8.0
script:
  - tox -e $TOX_ENV
after_script:
  - cat .tox/$TOX_ENV/log/*.log
